pub const USB_TIMEOUT_SECONDS: u8 = 1;

pub const GOOGLE_VID: u16 = 0x18D1;
pub const AOA_PID: u16 = 0x2D00;
pub const AOA_WITH_ADB_PID: u16 = 0x2D01;

pub const REQUEST_TYPE_GET_PROTOCOL: u8 = 51;
pub const REQUEST_TYPE_SEND_STRING: u8 = 52;
pub const REQUEST_TYPE_START_AOA: u8 = 53;
//pub const REQUEST_TYPE_SET_CONFIGURATION: u8 = 0x09;

pub const ACCESSORY_STRING_MANUFACTURER: u16 = 0;
pub const ACCESSORY_STRING_MODEL: u16 = 1;
pub const ACCESSORY_STRING_DESCRIPTION: u16 = 2;
pub const ACCESSORY_STRING_VERSION: u16 = 3;
pub const ACCESSORY_STRING_URI: u16 = 4;
pub const ACCESSORY_STRING_SERIAL: u16 = 5;
